services:
  - type: worker
    name: discord-music-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    autoDeploy: true
    # Render automatically includes FFmpeg in Python environment